# Generated by Django 2.2.3 on 2019-07-31 19:57

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('body', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pub_date', models.DateTimeField(blank=True)),
                ('comments_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
