# Generated by Django 2.2.3 on 2019-09-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
            ],
        ),
    ]
